"""
Conductor workspace/session identity adapter.

This is NOT an AgentAdapter. AgentAdapter (heyvox/adapters/base.py) handles
auto-send-decision logic (enter_count, should_auto_send). This adapter handles
workspace/session identity reads from Conductor's sqlite DB. They live in the
same package only because both are app-specific bridges.

SOLE owner of Conductor sqlite coupling — any schema change touches this file
only (Phase 15 SPEC R3). Callers get stable IDs (workspaces.id,
workspaces.active_session_id) that survive display-name renames.

On any sqlite error (missing file, locked DB, schema mismatch, WAL contention)
the adapter fails silently to None so the resolver's Tier 2/3 ladder can carry
on without a crash.
"""

import os
import sqlite3
import sys
from dataclasses import dataclass
from typing import Optional


DEFAULT_DB_PATH = os.path.expanduser(
    "~/Library/Application Support/com.conductor.app/conductor.db"
)


def _log(msg: str) -> None:
    try:
        print(f"[conductor-adapter] {msg}", file=sys.stderr, flush=True)
    except (BrokenPipeError, OSError):
        pass


@dataclass(frozen=True)
class ConductorIdentity:
    """Stable identity record for a Conductor workspace + active session.

    Fields are the literal column values from the `workspaces` table — not
    display names. Survives workspace rename / directory move because the
    primary key is an opaque ID generated by Conductor at workspace creation.
    """

    workspace_id: str
    session_id: Optional[str]
    branch: str
    directory_name: str


def get_active_workspace_and_session(
    directory_name: Optional[str] = None,
    branch: Optional[str] = None,
    db_path: Optional[str] = None,
) -> Optional[ConductorIdentity]:
    """Look up the active Conductor workspace + session by directory or branch.

    Args:
        directory_name: Workspace directory basename (e.g. "seattle"). If None,
            matches any directory.
        branch: Git branch name (e.g. "main"). If None, matches any branch.
        db_path: Override for the sqlite DB path. Defaults to DEFAULT_DB_PATH.
            Callers driven by `AppProfileConfig.workspace_db` (D-23) pass that
            value here so the profile remains the single source of truth.

    Returns:
        ConductorIdentity with stable IDs, or None on any failure (missing DB,
        locked DB, schema mismatch, no matching ready workspace, etc). Failures
        are logged to stderr with the `[conductor-adapter]` prefix.

    Notes:
        W9 — the `sqlite3.Error` branch of the except clause catches
        `sqlite3.OperationalError: database is locked` which is the normal
        signal from WAL contention with a live Conductor process. Do NOT
        tighten this to `OSError` only — the locked-DB test regression-guards
        this. D-20 explicitly calls out WAL contention as an expected failure
        mode that MUST be swallowed silently.
    """
    path = db_path if db_path is not None else DEFAULT_DB_PATH

    conn = None
    try:
        conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True, timeout=2)
        row = conn.execute(
            """
            SELECT id, active_session_id, branch, directory_name
            FROM workspaces
            WHERE (directory_name = ?1 OR ?1 IS NULL)
              AND (branch = ?2 OR ?2 IS NULL)
              AND state = 'ready'
            LIMIT 1
            """,
            (directory_name, branch),
        ).fetchone()
    except (sqlite3.Error, OSError) as e:
        _log(f"lookup failed: {e}")
        return None
    finally:
        if conn is not None:
            try:
                conn.close()
            except (sqlite3.Error, OSError):
                pass

    if row is None:
        _log(
            f"lookup ok: no ready workspace matched "
            f"(directory_name={directory_name!r}, branch={branch!r})"
        )
        return None

    identity = ConductorIdentity(
        workspace_id=row[0],
        session_id=row[1],
        branch=row[2] or "",
        directory_name=row[3] or "",
    )
    _log(
        f"lookup ok: workspace_id={identity.workspace_id} "
        f"session_id={identity.session_id} branch={identity.branch!r} "
        f"directory_name={identity.directory_name!r}"
    )
    return identity
