"""
Conductor workspace/session identity adapter.

This is NOT an AgentAdapter. AgentAdapter (heyvox/adapters/base.py) handles
auto-send-decision logic (enter_count, should_auto_send). This adapter handles
workspace/session identity reads from Conductor's sqlite DB. They live in the
same package only because both are app-specific bridges.

SOLE owner of Conductor sqlite coupling — any schema change touches this file
only (Phase 15 SPEC R3). Callers get stable IDs (workspaces.id,
workspaces.active_session_id) that survive display-name renames.

On any sqlite error (missing file, locked DB, schema mismatch, WAL contention)
the adapter fails silently to None so the resolver's Tier 2/3 ladder can carry
on without a crash.
"""

import os
import sqlite3
import sys
from dataclasses import dataclass
from typing import Optional


DEFAULT_DB_PATH = os.path.expanduser(
    "~/Library/Application Support/com.conductor.app/conductor.db"
)


def _log(msg: str) -> None:
    try:
        print(f"[conductor-adapter] {msg}", file=sys.stderr, flush=True)
    except (BrokenPipeError, OSError):
        pass


@dataclass(frozen=True)
class ConductorIdentity:
    """Stable identity record for a Conductor workspace + active session.

    Fields are the literal column values from the `workspaces` table — not
    display names. Survives workspace rename / directory move because the
    primary key is an opaque ID generated by Conductor at workspace creation.
    """

    workspace_id: str
    session_id: Optional[str]
    branch: str
    directory_name: str


def get_active_workspace_and_session(
    directory_name: Optional[str] = None,
    branch: Optional[str] = None,
    db_path: Optional[str] = None,
) -> Optional[ConductorIdentity]:
    """Look up the active Conductor workspace + session by directory or branch.

    Args:
        directory_name: Workspace directory basename (e.g. "seattle"). If None,
            matches any directory.
        branch: Git branch name (e.g. "main"). If None, matches any branch.
        db_path: Override for the sqlite DB path. Defaults to DEFAULT_DB_PATH.
            Callers driven by `AppProfileConfig.workspace_db` (D-23) pass that
            value here so the profile remains the single source of truth.

    Returns:
        ConductorIdentity with stable IDs, or None on any failure (missing DB,
        locked DB, schema mismatch, no matching ready workspace, etc). Failures
        are logged to stderr with the `[conductor-adapter]` prefix.

    Notes:
        W9 — the `sqlite3.Error` branch of the except clause catches
        `sqlite3.OperationalError: database is locked` which is the normal
        signal from WAL contention with a live Conductor process. Do NOT
        tighten this to `OSError` only — the locked-DB test regression-guards
        this. D-20 explicitly calls out WAL contention as an expected failure
        mode that MUST be swallowed silently.
    """
    path = db_path if db_path is not None else DEFAULT_DB_PATH

    conn = None
    try:
        conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True, timeout=2)
        row = conn.execute(
            """
            SELECT id, active_session_id, branch, directory_name
            FROM workspaces
            WHERE (directory_name = ?1 OR ?1 IS NULL)
              AND (branch = ?2 OR ?2 IS NULL)
              AND state = 'ready'
            LIMIT 1
            """,
            (directory_name, branch),
        ).fetchone()
    except (sqlite3.Error, OSError) as e:
        _log(f"lookup failed: {e}")
        return None
    finally:
        if conn is not None:
            try:
                conn.close()
            except (sqlite3.Error, OSError):
                pass

    if row is None:
        _log(
            f"lookup ok: no ready workspace matched "
            f"(directory_name={directory_name!r}, branch={branch!r})"
        )
        return None

    identity = ConductorIdentity(
        workspace_id=row[0],
        session_id=row[1],
        branch=row[2] or "",
        directory_name=row[3] or "",
    )
    _log(
        f"lookup ok: workspace_id={identity.workspace_id} "
        f"session_id={identity.session_id} branch={identity.branch!r} "
        f"directory_name={identity.directory_name!r}"
    )
    return identity


# ---------------------------------------------------------------------------
# WorkspaceProvider implementation (registered as "conductor" in
# heyvox.adapters.get_workspace_provider)
# ---------------------------------------------------------------------------

def detect_visible_branch(pid: int) -> str:
    """Walk Conductor's AX tree to find the branch name shown in the right panel.

    Conductor's UI shows the branch name in the right pane after the AXSplitter;
    walking AXFocusedWindow -> AXChildren -> past the splitter -> into the title
    bar of the right pane gives us the branch string. This is what's currently
    visible to the user (NOT what state the DB is in — the user may have
    workspaces in 'ready' state that aren't on screen).

    Returns the branch string or "" on any failure (caller treats "" as
    "context unknown — skip resolve, leave workspace_id None").

    Moved here from heyvox.input.target: this is Conductor-AX knowledge and
    belongs with the sole owner of Conductor coupling.
    """
    try:
        from ApplicationServices import (
            AXUIElementCreateApplication,
            AXUIElementCopyAttributeValue,
        )
        ax = AXUIElementCreateApplication(pid)
        # Try AXFocusedWindow first, then AXMainWindow, then first of AXWindows.
        win = None
        for attr in ("AXFocusedWindow", "AXMainWindow"):
            err, w = AXUIElementCopyAttributeValue(ax, attr, None)
            if err == 0 and w is not None:
                win = w
                break
        if win is None:
            err, windows = AXUIElementCopyAttributeValue(ax, "AXWindows", None)
            if err == 0 and windows and len(windows) > 0:
                win = windows[0]
        if win is None:
            return ""

        # Flatten the tree looking for the first AXStaticText after the first AXSplitter
        items: list[tuple[str, str]] = []  # (role, value)

        def _collect(elem, depth: int = 0) -> None:
            if depth > 6 or len(items) > 300:
                return
            err_r, role = AXUIElementCopyAttributeValue(elem, "AXRole", None)
            r = str(role) if err_r == 0 and role else ""
            err_v, val = AXUIElementCopyAttributeValue(elem, "AXValue", None)
            v = str(val).strip() if err_v == 0 and val else ""
            items.append((r, v))
            err_c, children = AXUIElementCopyAttributeValue(elem, "AXChildren", None)
            if err_c == 0 and children:
                for c in children:
                    _collect(c, depth + 1)

        _collect(win)

        past_splitter = False
        for r, v in items:
            if r == "AXSplitter":
                if past_splitter:
                    break
                past_splitter = True
                continue
            if past_splitter and r == "AXStaticText" and v:
                return v
        return ""
    except Exception as e:
        _log(f"detect_visible_branch: exception: {e}")
        return ""


class ConductorWorkspaceProvider:
    """WorkspaceProvider for Conductor (see heyvox.adapters.base).

    detect_context = the AX branch walk above (fast, in-thread);
    resolve = the sqlite identity lookup (may block — callers timeout it).
    """

    name = "conductor"

    def detect_context(self, pid: int) -> str:
        return detect_visible_branch(pid)

    def resolve(self, context, profile):
        from heyvox.adapters.base import WorkspaceIdentity
        workspace_db = getattr(profile, "workspace_db", "") if profile else ""
        db_path = os.path.expanduser(workspace_db) if workspace_db else None
        identity = get_active_workspace_and_session(
            directory_name=None, branch=context, db_path=db_path,
        )
        if identity is None:
            return None
        return WorkspaceIdentity(
            workspace_id=identity.workspace_id,
            session_id=identity.session_id,
        )
